# SPDX-PackageName: jtlvi
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://codeberg.org/rfinnie/jtlvi
# SPDX-FileCopyrightText: © 2020 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MIT

[project]
name = "jtlvi"
authors = [
    {name = "Ryan Finnie", email = "ryan@finnie.org"},
]
description = "JTLVI Message Format: Just TLV It!"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = []
dynamic = ["version"]

[project.urls]
Homepage = "https://codeberg.org/rfinnie/jtlvi"

[build-system]
requires = ["setuptools>=59.6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "jtlvi",
    "jtlvi.tests",
]

[tool.setuptools.dynamic]
version = {attr = "jtlvi.__version__"}

[tool.black]
line-length = 132
